version: "3.3"
services:
  app:
    image: chialab/php:8.1-fpm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    privileged: true
    pid: host
    networks:
      - php-app
    restart: always

  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - 88:80
    networks:
      - php-app
    restart: always

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - php-app

  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    networks:
      - php-app
    environment:
      MYSQL_ROOT_PASSWORD: php-app
      MYSQL_DATABASE: urls
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: url-shorter
    networks:
      - php-app

networks:
  php-app:
    driver: bridge

volumes:
  cache:
    driver: local